- name: add host to group 'just_created' with variable foo=42
  add_host:
    name: "{{ item }}"
    groups: webinstances
    web_admin: reddyguvvala79@gmail.com
    ansible_user: ec2-user
    ansible_ssh_private_key_file: /home/ec2-user/environment/webkey.pem
    ansible_become: yes
    ansible_connection: ssh
  loop:
    "{{ webinstance_output | json_query('results[*].tagged_instances[0].dns_name') }}"