  - name: install the latest version of Apache
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - httpd
      - mariadb-server
    register: installoutput
  - debug:
      var: installoutput
  - name: Copy configuration
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf   
    notify: "myrestart services"
  - name: Copy code
    template:
      src: index.j2
      dest: /var/www/html/index.html
  - name: Start service httpd, if not started
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - httpd
      - mariadb